setup:
	chmod +x gradlew && ./gradlew clean install



run-dist:
	java -cp . gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain run --console=plain

test:
	java -cp . gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain test